dailoantrongtoi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('index.urls'), name='index'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# urlpatterns += staticfiles_urlpatterns()

index/urls.py
from django.urls import path, re_path

from . import views

from .views import getItemListNews, getIndexCategory, patchRegister

app_name = "home"

urlpatterns = [
    
    # re_path(r'',views.media, name='media'),
    path('', views.indexViews.as_view(), name='index'),
    path('category/news/<int:pk>/',views.getItemListNews.as_view(),  name='detailID'),
    path('news/<slug:slug>', views.getItemListNews.as_view(),  name='detail'),
    path('category/<int:pk>/',getIndexCategory.as_view(), name='category'),
    path('register/', views.register, name="register"),
]

index/templates/footer.html
<footer>
    <div class="container">
        <div class="ct-footer">
            <div class="row align-center">
                <div class="col-lg-2">
                    <div class="logo">
                        <a href="#">
                            <img class="img-fluid" src="images/home/logo.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="cpr">
                        <strong>Copyright 2017</strong>, All rights reserved
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="arp">
                        © THÔNG TIN TỔNG HỢP TAIWAN™
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if insertScriptFooter %}
        {{insertScriptFooter.script | safe}}
    {% endif %}
</footer>

index/templates/header.html
{% load static %}
<header>
    <div class="container">
        <div class="d-flex position-relative">
            
            <div class="logo">
                <a href="{% url 'home:index' %}"><img class="img-fluid" src="{{Logo.image_logoOrBanner.url}}" alt=""></a>
            </div>
            <!-- BANNER -->
            <div class="banner-header">
                <img src="{{Banner.image_logoOrBanner.url}}" class="" alt="">
            </div>
            {% comment %} <div class="header-search">
                <form action="">
                    <div class="form-group">
                        <input type="text" name="" id="" class="form-control" placeholder="Tìm kiếm" aria-describedby="helpId">
                        <button type="submit" class="btn btn-submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 22 22" fill="none">
                                <path d="M21.4999 21.5L15.8999 15.9" stroke="#969696" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                                <path d="M9.5 18.5C14.4706 18.5 18.5 14.4706 18.5 9.5C18.5 4.52944 14.4706 0.5 9.5 0.5C4.52944 0.5 0.5 4.52944 0.5 9.5C0.5 14.4706 4.52944 18.5 9.5 18.5Z" stroke="#969696" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                        </button>
                    </div>
                </form>
            </div> {% endcomment %}
            <div class="user d-lg-none">
                <ul class="d-none">
                    <li><a href="login.html"><i class="fa fa-user" aria-hidden="true"></i> Đăng nhập</a></li>
                    <li><a href="register.html"><i class="fa fa-user-o" aria-hidden="true"></i> Tạo tài khoản</a></li>
                </ul>
                <div class="log">
                    <div class="log-thumb">
                        <img src="{% static 'images/home/default.jpg' %}" alt="">
                    </div>
                    <div class="log--ct">
                        <div class="log-ct-name">
                            Username
                        </div>
                        <a class="log-ct-out" href="#">( Thoát )</a>
                    </div>
                </div>
            </div>
            <div class="open-sidemenu">
                <div class="icon-bar"></div>
                <div class="icon-bar"></div>
                <div class="icon-bar"></div>
            </div>
        </div>
    </div>
</header>

<nav class="menu sticky-top" id="sidenav">
    <div class="container">
        <ul class="main">
            <li>
                <a href="{% url 'home:index' %}" class="active home"><i class="fa fa-home"></i></a>
            </li>
            {% for menu in Menus %}
                {% if not menu.menu_parent %}
                    <li>
                        <a href="{% url 'home:category' pk=menu.pk %}">{{ menu.title }} </a>
                        {% if menu.is_menu_parent %}
                            <svg class="accodition" xmlns="http://www.w3.org/2000/svg" width="10" height="6"
                                viewBox="0 0 10 6" fill="none">
                                <path
                                    d="M0.669162 0.629922C0.615535 0.685235 0.572992 0.750919 0.543966 0.82322C0.51494 0.89552 0.5 0.973019 0.5 1.05129C0.5 1.12955 0.51494 1.20705 0.543966 1.27935C0.572992 1.35165 0.615535 1.41734 0.669162 1.47265L4.58694 5.52101C4.64051 5.57638 4.70412 5.62031 4.77414 5.65028C4.84416 5.68025 4.91922 5.69568 4.99501 5.69568C5.07081 5.69568 5.14587 5.68025 5.21589 5.65028C5.28591 5.62031 5.34952 5.57638 5.40309 5.52101L9.32087 1.47265C9.37663 1.41784 9.42121 1.35207 9.45197 1.27919C9.48272 1.20632 9.49904 1.12783 9.49996 1.04834C9.50088 0.96885 9.48637 0.889977 9.4573 0.816368C9.42823 0.742759 9.38519 0.675904 9.3307 0.619744C9.27622 0.563583 9.2114 0.519253 9.14006 0.489368C9.06872 0.459483 8.99231 0.444647 8.91533 0.445735C8.83835 0.446822 8.76236 0.46381 8.69184 0.4957C8.62132 0.527588 8.5577 0.573733 8.50472 0.631411L4.99501 4.25841L1.48531 0.631412C1.43183 0.57594 1.3683 0.531895 1.29833 0.501796C1.22836 0.471697 1.15333 0.456133 1.07753 0.455995C1.00173 0.455856 0.926654 0.471147 0.856583 0.500991C0.786511 0.530834 0.722824 0.574646 0.669162 0.629922Z"
                                    fill="#25292C" />
                            </svg>
                            <ul class="sub-menu">
                                {% for sub_menu in Menus %}
                                    {% if sub_menu.menu_parent == menu.id %}
                                        <li>
                                            <a href="{% url 'home:category' pk=sub_menu.pk %}"> {{sub_menu.title}} </a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </li>
                {% endif %}
            {% endfor %}
             <li class="moveTo">
               <a class="search-icon" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 22 22" fill="none">
                        <path d="M21.4999 21.5L15.8999 15.9" stroke="#969696" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M9.5 18.5C14.4706 18.5 18.5 14.4706 18.5 9.5C18.5 4.52944 14.4706 0.5 9.5 0.5C4.52944 0.5 0.5 4.52944 0.5 9.5C0.5 14.4706 4.52944 18.5 9.5 18.5Z" stroke="#969696" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                </a>
            </li>
        </ul>
    </div>
</nav>
<!-- overlay -->
<div class="block-overlay"></div>
<!-- /.overlay -->
<!-- header -->

index/templates/new-hot.html
{% load static %}
<!-- right -->
<div class="col-lg-4">
    <div class="side-ct">
        <div class="side-widget">
            <h4 class="heading">
                 ĐƠN HÀNG XKLĐ ĐÀI LOAN HOT
            </h4>
            <div class="list-popular">
                {% for news in news_holy_gvgd %}
                    <div class="news-item">
                        <div class="row ">
                            <div class="col-6 ">
                                <div class="ct">
                                    <h6 class="title">
                                        <a href="{% url 'home:detail' slug=news.slug %}">{{news.description | safe}}</a>
                                    </h6>
                                    <div class="tag">
                                        <a href="{% url 'home:category' pk=news.category.pk %}">#{{news.category.title}}</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 ">
                                <div class="thumb">
                                    <a href="{% url 'home:detail' slug=news.slug %}">
                                        <img class="img-fluid" src="{{news.avata.url}}" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                {% for news in news_duhoc_dailoan %}
                    <div class="news-item">
                        <div class="row ">
                            <div class="col-6 ">
                                <div class="ct">
                                    <h6 class="title">
                                        <a href="{% url 'home:detail' slug=news.slug %}">{{news.description | safe}}</a>
                                    </h6>
                                    <div class="tag">
                                        <a href="{% url 'home:category' pk=news.category.pk %}">#{{news.category.title}}</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 ">
                                <div class="thumb">
                                    <a href="{% url 'home:detail' slug=news.slug %}">
                                        <img class="img-fluid" src="{{news.avata.url}}" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                {% for news in news_dainam %}
                    <div class="news-item">
                        <div class="row ">
                            <div class="col-6 ">
                                <div class="ct">
                                    <h6 class="title">
                                        <a href="{% url 'home:detail' slug=news.slug %}">{{news.description | safe}}</a>
                                    </h6>
                                    <div class="tag">
                                        <a href="{% url 'home:category' pk=news.category.pk %}">#{{news.category.title}}</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 ">
                                <div class="thumb">
                                    <a href="{% url 'home:detail' slug=news.slug %}">
                                        <img class="img-fluid" src="{{news.avata.url}}" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                {% for news in news_caohung_binhdong %}
                    <div class="news-item">
                        <div class="row ">
                            <div class="col-6 ">
                                <div class="ct">
                                    <h6 class="title">
                                        <a href="{% url 'home:detail' slug=news.slug %}">{{news.description | safe}}</a>
                                    </h6>
                                    <div class="tag">
                                        <a href="{% url 'home:category' pk=news.category.pk %}">#{{news.category.title}}</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 ">
                                <div class="thumb">
                                    <a href="{% url 'home:detail' slug=news.slug %}">
                                        <img class="img-fluid" src="{{news.avata.url}}" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% for news in news_daibac %}
                    <div class="news-item">
                        <div class="row ">
                            <div class="col-6 ">
                                <div class="ct">
                                    <h6 class="title">
                                        <a href="{% url 'home:detail' slug=news.slug %}">{{news.description | safe}}</a>
                                    </h6>
                                    <div class="tag">
                                        <a href="{% url 'home:category' pk=news.category.pk %}">#{{news.category.title}}</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 ">
                                <div class="thumb">
                                    <a href="{% url 'home:detail' slug=news.slug %}">
                                        <img class="img-fluid" src="{{news.avata.url}}" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                {% for news in news_daitrung %}
                    <div class="news-item">
                        <div class="row ">
                            <div class="col-6 ">
                                <div class="ct">
                                    <h6 class="title">
                                        <a href="{% url 'home:detail' slug=news.slug %}">{{news.description | safe}}</a>
                                    </h6>
                                    <div class="tag">
                                        <a href="{% url 'home:category' pk=news.category.pk %}">#{{news.category.title}}</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 ">
                                <div class="thumb">
                                    <a href="{% url 'home:detail' slug=news.slug %}">
                                        <img class="img-fluid" src="{{news.avata.url}}" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="side-widget">
            <h4 class="heading">
                Tin nổi bật
            </h4>
            <div class="list-nor">
                <div class="news-item news-item-hl">
                    <h6 class="title">
                        <a href="{% url 'home:detail' slug=newNews.slug %}">{{newNews.title}}</a>
                    </h6>
                    <div class="row roww align-center">
                        <div class="col-6 coll">
                            <div class="thumb">
                                <a href="#">
                                    <img class="img-fluid" src="{{newNews.avata.url}}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-6 coll">
                            <div class="desc">
                                {{newNews.description | safe}}
                            </div>
                        </div>
                    </div>
                </div>
                {% for news in newNews7 %}
                    <div class="news-item">
                        <h6 class="title">
                            <a href="{% url 'home:detail' slug=news.slug %}">{{news.description | safe}}</a>
                        </h6>
                    </div>
                {% endfor %}
                
            </div>

            <div class="side-widget">
                <h4 class="heading">
                    Người Việt Nam Tại Đài Loan
                </h4>
                <div id="fb-root">
                    <div id="fb-root"></div> <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v6.0&appId=597828661072832&autoLogAppEvents=1"></script><div class="fb-page" data-href="https://www.facebook.com/vietnamlaodongxaxu/" data-tabs="timeline" data-width="350" data-height="467" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/vietnamlaodongxaxu/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/vietnamlaodongxaxu/">Người Việt Nam Tại Đài Loan</a></blockquote></div>
                </div>
            </div>

            <div class="side-widget">
                <h4 class="heading">
                    Tin Đài Loan
                </h4>
                <div id="fb-root"></div>
                    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v8.0&appId=597828661072832&autoLogAppEvents=1" nonce="E9jBBfEA"></script>
                    <div class="fb-group" data-href="https://www.facebook.com/groups/httptindailoan.net" data-width="360" data-show-social-context="true" data-show-metadata="true"><blockquote cite="https://www.facebook.com/groups/httptindailoan.net" class="fb-xfbml-parse-ignore">Tin Đài Loan</blockquote></div>
            </div>

            <div class="side-widget">
                <h4 class="heading">
                    Đài Loan Chờ Tôi Nhé
                </h4>
                <div id="fb-root">
                    <div id="fb-root">
                        <div id="fb-root"></div>
                            <div id="fb-root"></div>
                            <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v6.0&appId=597828661072832&autoLogAppEvents=1"></script>
                            <div class="fb-page" data-href="https://www.facebook.com/donhangdailoan1/" data-tabs="timeline" data-width="350" data-height="400" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/donhangdailoan1/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/donhangdailoan1/">Đài Loan Chờ Tôi Nhé</a></blockquote></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.right -->

index/templates/news-single.html
{% extends "base.html" %}
{% load static %}
{% comment %} {% load staticfiles %} {% endcomment %}

{% block title%}{{object.title}}{% endblock %}
{% block image_logo%}
    <link rel="shortcut icon" type="image/x-icon" href="{{logohead.image_logoOrBanner.url}}" />
    <meta property="og:type" content="website" />
    <meta property="og:image"              content="{{object.avata.url}}" />
    <meta property="og:description"        content="&hellip;" />
    <meta property="og:title"              content="{{object.title}}" />
{% endblock %}

{% block content %} 

     <!-- header -->
    {% include "header.html" %}
    <!-- end-header -->

    <!-- main -->
    <div class="main-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <nav class="breadcrumb">
                        <a class="breadcrumb-item" href="{% url 'home:index' %}">Home</a>
                        <span class="breadcrumb-item active">{{object.category}}</span>
                    </nav>
                </div>
            </div>
            <div class="row">
                <!-- left -->
                <div class="col-lg-8">
                    <div class="single-post">
                        <article>
                            <h1>{{object.title}}</h1>
                            <div class="meta">
                                <div class="date">{{object.create_at}}</div>
                                <div class="author">{{object.author}}</div>
                            </div>
                            <img class="img-fluid" src="{{object.avata.url}}" alt="">
                            <div class="content-post">
                                {{object.content | safe}}
                            </div>
                        </article>
                        <div id="fb-root">
                            <meta property="og:image" content="{{object.avata.url}}" />
                            <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v6.0&appId=597828661072832&autoLogAppEvents=1"></script>
                            <div class="fb-share-button" data-href="{% url 'home:detail' slug=object.slug %}" data-layout="button_count" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Chia sẻ</a></div>
                        </div>
                        <div><span>Lượt khách xem bài viết: {{object.views_number}}</span></div>
                        
                    </div>
                    <div class="related-post">
                        <h4 class="heading">
                            Tin liên quan
                        </h4>
                        <ul>
                            {% for news in NewsRelateTo %}
                                <li>
                                    <a href="{% url 'home:detail' slug=news.slug %}">{{news.title}}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- /.left -->

                <!-- right -->
                {% include "new-hot.html" %}
                <!-- /.right -->
            </div>
        </div>
    </div>
    <!-- /.main -->

    <!-- footer -->
    <footer>
        <div class="container">
            <div class="ct-footer">
                <div class="row align-center">
                    <div class="col-lg-2">
                        <div class="logo">
                            <a href="#">
                                <img class="img-fluid" src="images/home/logo.png" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="cpr">
                            <strong>Copyright 2020</strong>, All rights reserved
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="arp">
                            © THÔNG TIN TỔNG HỢP TAIWAN™
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- /.footer -->

{% endblock %}
    

index/templates/news.html
{% extends "base.html" %}
{% comment %} {% load staticfiles %} {% endcomment %}


{% block title%}Danh mục tin tức{% endblock %}


{% block image_logo%}
    <link rel="shortcut icon" type="image/x-icon" href="{{logohead.image_logoOrBanner.url}}" />
{% endblock %}


{% block content %} 

    <!-- header -->
    {% include "header.html" %}
    <!-- end-header -->
    <!-- main -->
    <div class="main-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <nav class="breadcrumb">
                        <a class="breadcrumb-item" href="{% url 'home:index' %}">Home</a>
                        <span class="breadcrumb-item active">{{object_list.0.category.title}}</span>
                    </nav>
                </div>
            </div>
            

                {% if object_list.0.category.is_category %}

               
                <!-- main -->
                <div class="about-wp">
                    <div class="container">
                        <h1>{{object_list.0.title }}</h1>
                        <div class="content">
                            <p>
                                {{object_list.0.content | safe}}
                            </p>
                            <p class="text-center">
                                <img class="img-fluid" src="images/home/about.png" alt="">
                            </p>
                        </div>
                    </div>
                </div>

                <div class="contact-wp">
                    <div class="container">
                        <div class="row flex-reverse">
                            <div class="col-lg-6">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3723.7126676037224!2d105.77217741493286!3d21.044179885990037!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454cec92b48ef%3A0x21eda1d01b833b64!2zMTQ2IFRy4bqnbiBW4bu5LCBNYWkgROG7i2NoLCBD4bqndSBHaeG6pXksIEjDoCBO4buZaQ!5e0!3m2!1svi!2s!4v1583693566033!5m2!1svi!2s" width="555" height="457" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                            </div>
                            <div class="col-lg-6">
                                <h4>liên hệ với chúng tôi</h4>
                                <form action="">
                                    <div class="form-group">
                                        <label for="">Họ & Tên</label>
                                        <input type="text" name="" id="" class="form-control" placeholder="Ví dụ: Nguyễn Văn A" aria-describedby="helpId">
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <label for="">Số điện thoại</label>
                                                <input type="text" name="" id="" class="form-control" placeholder="Ví dụ: 0969310911" aria-describedby="helpId">
                                            </div>
                                        </div>
                                        <div class="col-md-7">
                                            <div class="form-group">
                                                <label for="">Email</label>
                                                <input type="text" name="" id="" class="form-control" placeholder="Ví dụ: nguyenvana@gmail.com" aria-describedby="helpId">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="">Họ & Tên</label>
                                        <textarea name="" id="" cols="30" rows="10"></textarea>
                                    </div>
                                    <div class="form-group text-right">
                                        <button type="submit" class="btn btn-submit">Gửi</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.main -->

                {% else %}
                 <div class="row">
                <!-- left -->
                <div class="col-lg-8">
                    <div class="list-news">
                        {% for news in object_list %}
                            <div class="news-hoz mb-2">
                                <div class="row roww">
                                    <div class="col-xl-3 col-5 coll">
                                        <div class="thumb mb-3">
                                            <a href="#">
                                                <img class="img-fluid" src="{{news.avata.url}}" alt="">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-xl-9 col-7 coll">
                                        <div class="ct">
                                            <h6 class="title">
                                                    
                                                <a href="{% url 'home:detail' slug=news.slug %}">{{news.title}}</a>
                                            </h6>
                                            <div class="desc">
                                                {{news.description | safe}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    {% if is_paginated %}
                        <nav class="text-center mt-3 mb-5">
                            <ul class="pagination">
                                <li>
                                    {% if page_obj.has_previous %}
                                    <a href="?page={{ page_obj.previous_page_number  }}" class="pagination-item next">Back</a>
                                    {% endif %}
                                </li>
                                <li>
                                    <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                                </li>
                                <li>
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}" class="pagination-item next">Next</a>
                                    {% endif %}
                                </li>
                            </ul>
                        </nav>
                    {% endif %}
                </div>
                <!-- /.left -->
                
                <!-- right -->
                {% include "new-hot.html" %}
                <!-- /.right -->
                
            </div>
            {% endif %}
        </div>
    </div>
    <!-- /.main -->

    <!-- footer -->
    {% include "footer.html" %}
    <!-- /.footer -->

{% endblock %}